### ISSUE TITLE
busybox Base image is deprecated

### ISSUE THREAD

**Issue by tgermain** [CiscoCloud/docker-logstash#3]
Hi, 
The busybox base image seems to be broken, or at least opkg is not working anymore. 

From what I've read it seems that Alpine is the replacement for low footprint base image. 

from docker-hub : 

OpenWRT switched from GLIBC to MUSL, which breaks progrium/busybox :( I'm switching to alpine based container, after installing glibc as described here: https://github.com/progrium/busybox/issues/24

and from https://github.com/progrium/busybox README

**Comment by ghost** [comment]
Hello,

Yes, this is one of the reasons why I started this issue: https://github.com/CiscoCloud/microservices-infrastructure/issues/596

Thank you, working on this right now.
